name: Gradle Önbellek Temizleyici

on:
  workflow_dispatch:  # Manuel tetikleme için
  schedule:
    - cron: '0 0 * * 0'  # Her Pazar günü gece yarısı çalıştır

jobs:
  clean-gradle-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Repoyu Kontrol Et
        uses: actions/checkout@v4

      - name: JDK 17'yi Kur
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Önbelleğini Temizle
        run: |
          chmod +x ./gradlew

          ./gradlew clean
          ./gradlew cleanBuildCache
          rm -rf ~/.gradle/caches/
          rm -rf ~/.gradle/wrapper/
          rm -rf .gradle
          rm -rf */build
          git add .
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -m "🧹 Gradle önbelleği temizlendi" || echo "Değişiklik yok"
          git push